# Generated by Django 4.2.3 on 2023-11-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
