# Generated by Django 4.1.7 on 2023-11-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Cod', 'Cash on Delivery')], default='Paypal', max_length=10),
        ),
    ]
